version: '3.8'
services:
  php:
    image: php:8.1-cli
    container_name: php_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba-tecnica
      MYSQL_USER: root
    ports:
      - "3306:3306"